#!/bin/sh

# Cleanup previous builds
rm -rf obj_dir
rm -f top.vcd

# Run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace top.sv counter.sv bin2bcd.sv --exe top_tb.cpp

# Build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop

# Run the executable simulation file
obj_dir/Vtop